version: "3.3"

services:

  plausible_db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      website:
        ipv4_address: 172.26.0.107

  plausible_events_db:
    image: yandex/clickhouse-server:latest
    volumes:
      - event-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      website:
        ipv4_address: 172.26.0.106

  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env
    networks:
      website:
        ipv4_address: 172.26.0.105


  database:
    build:
      context: ./database
    container_name: database
    ports: 
      - 6379:6379
    networks:
      website:
        ipv4_address: 172.26.0.104

  backend:
    build:
      context: ./backend
    container_name: backend
    ports: 
      - 5000:5000
    networks:
      website:
        ipv4_address: 172.26.0.103
    depends_on:
      - database

        
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports: 
      - 3000:3000
    networks:
      website:
        ipv4_address: 172.26.0.102
    depends_on:
      - backend

  webserver:
    build: 
      context: ./webserver
    container_name: webserver
    ports: 
      - 80:80
      - 443:443
    networks: 
      website:
        ipv4_address: 172.26.0.101
    depends_on: 
      - frontend

volumes:
  db-data:
    driver: local
  event-data:
    driver: local

networks:
  website:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24
