version: "3"

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      website:
        ipv4_address: 172.26.0.106

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - postgres:postgres
    volumes:
      - strapi-cms:/srv/app
    ports:
      - '1337:1337'
    networks:
      website:
        ipv4_address: 172.26.0.105

  database:
    build:
      context: ./database
    container_name: database
    ports: 
      - 6379:6379
    networks:
      website:
        ipv4_address: 172.26.0.104

  backend:
    build:
      context: ./backend
    container_name: backend
    ports: 
      - 5000:5000
    networks:
      website:
        ipv4_address: 172.26.0.103
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports: 
      - 3000:3000
    networks:
      website:
        ipv4_address: 172.26.0.102
    depends_on:
      - backend

  webserver:
    build: 
      context: ./webserver
    container_name: webserver
    ports: 
      - 80:80
      - 443:443
    networks: 
      website:
        ipv4_address: 172.26.0.101
    depends_on: 
      - frontend
      
volumes:
  postgres-db:
    driver: local
  strapi-cms:
    driver: local

networks:
  website:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24
