version: "3"

services:

  database:
    restart: always
    build:
      context: ./database
    container_name: prod_database
    networks:
      website:
        ipv4_address: 172.26.0.104

  backend:
    restart: always
    build:
      context: ./backend
    container_name: prod_backend
    networks:
      website:
        ipv4_address: 172.26.0.103
    depends_on:
      - database

        
  frontend:
    restart: always
    build:
      context: ./frontend
    container_name: prod_frontend
    networks:
      website:
        ipv4_address: 172.26.0.102
    depends_on:
      - backend

  webserver:
    restart: always
    build: 
      context: ./webserver
    container_name: prod_webserver
    ports: 
      - 80:80
      - 443:443
    networks: 
      website:
        ipv4_address: 172.26.0.101
    depends_on: 
      - frontend
      
networks:
  website:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24
