version: "3"

services:

  database:
    build:
      context: ./database
    container_name: database

    networks:
      website:
        ipv4_address: 172.26.0.104

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - 5000:5000
    expose:
      - 5000
    networks:
      website:
        ipv4_address: 172.26.0.103
    depends_on:
      - database

        
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      website:
        ipv4_address: 172.26.0.102
    depends_on:
      - backend

networks:
  website:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24
