version: "3"

services:
  frontend:
    privileged: true
    build:
      context: ./frontend
    container_name: frontend
    networks:
      website:
        ipv4_address: 172.26.0.102

networks:
  website:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24
